import Navbar from '@/components/Navbar';
import './globals.css';
import { Roboto } from 'next/font/google';
import { type ReactNode } from 'react';
import ThemeRegistry from '@/components/ThemeRegistry';

export const metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

const roboto = Roboto({
	subsets: ['latin'],
	weight: ['100', '300', '400', '500', '700', '900'],
	display: 'swap',
});

export default function RootLayout({ children }: { children: ReactNode }) {
	return (
		<html lang="en" className={roboto.className}>
			<ThemeRegistry>
				<body style={{ background: 'black' }}>
					<Navbar />
					{children}
				</body>
			</ThemeRegistry>
		</html>
	);
}
