import Navbar from '@/components/Navbar';
import './globals.css';
import { Roboto } from 'next/font/google';
import ThemeProvider from '@/components/ThemeProvider';
import { type ReactNode } from 'react';

export const metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

const roboto = Roboto({
	subsets: ['latin'],
	weight: ['100', '300', '400', '500', '700', '900'],
	display: 'swap',
});

export default function RootLayout({ children }: { children: ReactNode }) {
	return (
		<ThemeProvider>
			<html lang="en" className={roboto.className}>
				<body style={{ background: 'black' }}>
					<Navbar />
					{children}
				</body>
			</html>
		</ThemeProvider>
	);
}
